spring:
  profiles:
    active: dev

---
server:
  port: 8080

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:tcp://localhost/~/dev/inflearn/jpashop
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
